CREATE TABLE Bids (
    id SERIAL PRIMARY KEY,
    auction_id INT NOT NULL,
    bidder_id INT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (auction_id) REFERENCES Auctions(id) ON DELETE CASCADE,
    FOREIGN KEY (bidder_id) REFERENCES Users(id) ON DELETE CASCADE
);
